const ActionTypes = {
  SET_ALL_PROFILES: 'SET_ALL_PROFILES',
  GET_ALL_PROFILES: 'GET_ALL_PROFILES',
  GET_ALL_SCORES: 'GET_ALL_SCORES',
  SET_ALL_SCORES: 'SET_ALL_SCORES',
  SET_ALL_NEWS: 'SET_ALL_NEWS',
  GET_ALL_NEWS: 'GET_ALL_NEWS',
  SET_NEWS_ITEM: 'SET_NEWS_ITEM',
  SET_PROFILE: 'SET_PROFILE',
};

export default ActionTypes;
